#!/usr/bin/env bash
# observability-up.sh — stand up (or re-converge) the factory's observability
# stack on the runner host: an OTEL collector fronting a self-hosted Langfuse.
#
# Idempotent, and specifically KEY-STABLE: the generated credentials live in
# factory-ops/state/.bootstrap-runner/observability.env and are written exactly
# once. Regenerating them on a re-run would hand Langfuse a new project key
# while the old project keeps every trace already ingested — the UI would look
# empty and the collector would look healthy. If you truly want fresh
# credentials, delete the env file and the langfuse_* volumes together.
#
# Usage:  scripts/observability-up.sh            # up + prove the stack works
#         FACTORY_OBS_WAIT=0 scripts/…           # up only — proves NOTHING, so
#                                                # it exits non-zero; never use
#                                                # it from bootstrap.sh
#         FACTORY_OBS_WAIT_TRIES=n scripts/…     # health attempts, 5s apart
#
# Exit code is the contract: 0 means "langfuse is healthy AND accepted the
# collector's credentials", and nothing weaker. bootstrap.sh publishes the
# FACTORY_OTEL_ENDPOINT repo variable on that basis alone.
#
# Progress goes to stderr; stdout prints only the endpoint the runner dials.
set -euo pipefail
cd "$(dirname "$0")/.."

log()  { printf '>> %s\n' "$*" >&2; }
warn() { printf '!! %s\n' "$*" >&2; }
die()  { printf 'FATAL: %s\n' "$*" >&2; exit 1; }

STATE_DIR="factory-ops/state/.bootstrap-runner"
ENV_FILE="$STATE_DIR/observability.env"
COMPOSE_FILE="docker-compose.observability.yml"
# The name the runner container resolves on factory-net (compose alias +
# container_name). Keep in sync with docker-compose.observability.yml.
RUNNER_ENDPOINT="http://factory-collector:4318"

command -v docker >/dev/null 2>&1 || die "docker is required to run the observability stack"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (docker-compose v1 is not supported)"
[ -f "$COMPOSE_FILE" ] || die "$COMPOSE_FILE not found — run this from the repo root"

# rand_hex <bytes> — hex secret, openssl when present, /dev/urandom otherwise.
# Hex on purpose: compose interpolates its env file, so a value carrying '$'
# would be silently mangled into something neither side can reproduce.
rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

b64() {
  if command -v openssl >/dev/null 2>&1; then printf '%s' "$1" | openssl base64 -A
  else printf '%s' "$1" | base64 | tr -d '\n'; fi
}

# --- credentials (written once) ----------------------------------------------
if [ -f "$ENV_FILE" ]; then
  log "reusing existing credentials ($ENV_FILE)"
else
  log "generating credentials → $ENV_FILE"
  mkdir -p "$STATE_DIR"
  pk="pk-lf-$(rand_hex 16)"
  sk="sk-lf-$(rand_hex 16)"
  # umask before the first write: the file must never exist, even for an
  # instant, with world-readable permissions.
  ( umask 077
    cat > "$ENV_FILE" <<ENVEOF
# Generated by scripts/observability-up.sh — host-local, never committed.
# Deleting this file orphans every trace already stored under the project key
# below; delete the langfuse_* docker volumes at the same time if you do.
POSTGRES_PASSWORD=$(rand_hex 24)
CLICKHOUSE_USER=langfuse
CLICKHOUSE_PASSWORD=$(rand_hex 24)
REDIS_AUTH=$(rand_hex 24)
MINIO_ROOT_USER=langfuse
MINIO_ROOT_PASSWORD=$(rand_hex 24)
SALT=$(rand_hex 24)
ENCRYPTION_KEY=$(rand_hex 32)
NEXTAUTH_SECRET=$(rand_hex 24)
LANGFUSE_INIT_ORG_ID=dark-software-factory
LANGFUSE_INIT_ORG_NAME=Dark Software Factory
LANGFUSE_INIT_PROJECT_ID=factory
LANGFUSE_INIT_PROJECT_NAME=factory
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=$pk
LANGFUSE_INIT_PROJECT_SECRET_KEY=$sk
LANGFUSE_INIT_USER_EMAIL=factory@localhost
LANGFUSE_INIT_USER_NAME=factory
LANGFUSE_INIT_USER_PASSWORD=$(rand_hex 16)
LANGFUSE_OTLP_ENDPOINT=http://langfuse-web:3000/api/public/otel
LANGFUSE_OTLP_AUTHORIZATION=Basic $(b64 "$pk:$sk")
ENVEOF
  )
  chmod 600 "$ENV_FILE"
fi

# --- the runner's network ----------------------------------------------------
# bootstrap.sh (§8) owns factory-net; create it here only so this script also
# works on a host where the observability stack is stood up first.
docker network inspect factory-net >/dev/null 2>&1 || {
  log "creating factory-net (the runner's network)"
  docker network create factory-net >/dev/null
}

# --- up ----------------------------------------------------------------------
log "starting the observability stack (collector + langfuse)"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d >&2

# --- health + proof ----------------------------------------------------------
# Langfuse runs its clickhouse + postgres migrations on first boot; a couple of
# minutes cold is normal, and the collector's queue holds anything emitted
# meanwhile. Only report success on a real 200 from the health endpoint.
#
# THE EXIT CODE IS THE CONTRACT. bootstrap.sh (§8b) gates the
# FACTORY_OTEL_ENDPOINT repo variable on nothing but this script's exit status,
# so every way of failing to prove the stack — never healthy, credentials
# rejected, endpoint unreachable — has to reach `exit 1`. A branch that only
# warns publishes the endpoint anyway and wires every station to a pipeline that
# silently drops its traces: the precise inversion this design exists to
# prevent. Pinned by the exit-code drive in tests/observability.contract.test.sh.
PROVEN=false
if [ "${FACTORY_OBS_WAIT:-1}" = "1" ]; then
  log "waiting for langfuse to answer on 127.0.0.1:3000 (first boot runs migrations)"
  healthy=false
  for _ in $(seq 1 "${FACTORY_OBS_WAIT_TRIES:-60}"); do
    if curl -fsS --noproxy '*' --max-time 5 http://127.0.0.1:3000/api/public/health >/dev/null 2>&1; then
      healthy=true
      break
    fi
    sleep 5
  done
  if [ "$healthy" = true ]; then
    log "langfuse is healthy — UI at http://127.0.0.1:3000 (ssh -N -L 3000:127.0.0.1:3000 <host>)"
    log "sign in with the credentials in $ENV_FILE (LANGFUSE_INIT_USER_*)"

    # A healthy Langfuse is not a working pipeline. The collector authenticates
    # with the Basic credentials generated above, and if Langfuse rejects them
    # the collector's retry + sending queue swallows the 401: exports look
    # accepted from the runner's side, the collector logs stay quiet at warn
    # level, and the UI simply stays empty. So prove the credential pair against
    # the same OTLP endpoint the collector posts to, before declaring success.
    #
    # Proof is 2xx (accepted) or 400 (read the credentials, rejected the
    # deliberately-empty payload) — and NOTHING else. Treating every non-401 as
    # success is the same mistake as not checking at all: a 404 means the OTLP
    # path moved out from under the collector's exporter, and a 5xx means the
    # backend is wedged. Both drop traces exactly as silently as a bad key.
    auth="$(sed -n 's/^LANGFUSE_OTLP_AUTHORIZATION=//p' "$ENV_FILE" | head -1)"
    # `|| code=000` on the ASSIGNMENT, not inside the substitution: a curl that
    # cannot connect writes its own "000" from -w AND exits non-zero, so an
    # `|| echo 000` inside would concatenate two codes into a string that
    # matches no case branch and reports a connection failure as success.
    code="$(curl -s -o /dev/null -w '%{http_code}' --noproxy '*' --max-time 10 \
      -X POST http://127.0.0.1:3000/api/public/otel/v1/traces \
      -H "Authorization: $auth" -H 'Content-Type: application/json' \
      -d '{"resourceSpans":[]}' 2>/dev/null)" || code=000
    case "$code" in
      2??|400)
        log "langfuse accepted the collector's credentials (HTTP $code) — the trace path is live"
        PROVEN=true
        ;;
      401|403)
        warn "langfuse REJECTED the collector's credentials (HTTP $code) — traces would be dropped silently"
        warn "the project keys in $ENV_FILE do not match the project langfuse initialised."
        warn "that happens when the env file was regenerated against existing langfuse_* volumes."
        warn "fix: docker compose -f $COMPOSE_FILE down -v, delete $ENV_FILE, and re-run this script"
        ;;
      404)
        warn "langfuse has no OTLP endpoint at /api/public/otel/v1/traces (HTTP 404)"
        warn "the collector's exporter posts exactly there — check the langfuse image version in $COMPOSE_FILE"
        ;;
      5??)
        warn "langfuse returned HTTP $code from its OTLP endpoint — the backend is not serving ingestion"
        warn "check 'docker compose -f $COMPOSE_FILE logs langfuse-web langfuse-worker clickhouse'"
        ;;
      000)
        warn "could not reach the langfuse OTLP endpoint — the credentials are UNVERIFIED"
        warn "unverified is not the same as working: refusing to report a stack we could not prove"
        ;;
      *)
        warn "unexpected HTTP $code from the langfuse OTLP endpoint — treating the trace path as unproven"
        ;;
    esac
  else
    warn "langfuse did not become healthy — 'docker compose -f $COMPOSE_FILE logs langfuse-web'"
    warn "the collector is still up and queuing; re-run this script once langfuse recovers"
  fi
else
  # An explicit "don't wait" means nothing was proven. The stack may be fine —
  # this script just cannot say so, and saying so is its entire job here.
  warn "FACTORY_OBS_WAIT=0 — skipped the health wait and the credential proof; the stack is UNVERIFIED"
fi

if [ "$PROVEN" != true ]; then
  warn "the observability stack is NOT proven — not reporting an endpoint"
  warn "sessions will run without telemetry until this script exits 0"
  exit 1
fi

log "collector: OTLP/HTTP on 127.0.0.1:4318 (host) and $RUNNER_ENDPOINT (factory-net)"
log "metrics:   prometheus scrape on 127.0.0.1:8889/metrics"
printf '%s\n' "$RUNNER_ENDPOINT"
